# Generated by Django 3.2.5 on 2024-05-10 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='valuee',
            new_name='value',
        ),
    ]
